import type { Product } from "@/types/product";

function variants(sizes: string[], sku: string): Product["variants"] {
  return sizes.map((size, i) => ({
    id: `${sku}-${i}`,
    size,
    stock: [8, 12, 3, 0][i % 4],
    sku: `${sku}-${size.replace(/\s+/g, "").toUpperCase()}`,
  }));
}

export const seedProducts: Product[] = [
  {
    id: "prod-aurora-solitaire",
    name: "Aurora Solitaire Ring",
    slug: "aurora-solitaire-ring",
    description:
      "A single brilliant-cut stone set in a delicate band, designed for everyday elegance. The Aurora catches light from every angle without overwhelming the hand.",
    price: 42500,
    compareAtPrice: 48000,
    categoryId: "cat-rings",
    material: "18k Gold Plated · Cubic Zirconia",
    variants: variants(["Size 5", "Size 6", "Size 7", "Size 8"], "AUR-SOL"),
    status: "active",
    featured: true,
    createdAt: "2026-01-05T00:00:00.000Z",
  },
  {
    id: "prod-stacked-eternity",
    name: "Eternity Stack Band",
    slug: "eternity-stack-band",
    description:
      "A slim band lined edge-to-edge with pave stones, made to be worn alone or layered with your other rings.",
    price: 31000,
    categoryId: "cat-rings",
    material: "925 Sterling Silver · Cubic Zirconia",
    variants: variants(["Size 5", "Size 6", "Size 7", "Size 8"], "ETB"),
    status: "active",
    createdAt: "2026-01-06T00:00:00.000Z",
  },
  {
    id: "prod-ivory-pearl-necklace",
    name: "Ivory Pearl Necklace",
    slug: "ivory-pearl-necklace",
    description:
      "Freshwater pearls strung along a fine gold-plated chain, finished with a single pendant drop for quiet, everyday polish.",
    price: 58000,
    categoryId: "cat-necklaces",
    material: "18k Gold Plated · Freshwater Pearl",
    variants: variants(['16"', '18"'], "IPN"),
    status: "active",
    featured: true,
    createdAt: "2026-01-04T00:00:00.000Z",
  },
  {
    id: "prod-lariat-pendant",
    name: "Lariat Pendant Necklace",
    slug: "lariat-pendant-necklace",
    description:
      "An open-front pendant on a fine chain, sitting just below the collarbone. Pairs easily with layered looks.",
    price: 36500,
    categoryId: "cat-necklaces",
    material: "Rose Gold Plated Brass",
    variants: variants(['18"'], "LPN"),
    status: "active",
    createdAt: "2026-01-07T00:00:00.000Z",
  },
  {
    id: "prod-halo-studs",
    name: "Halo Drop Studs",
    slug: "halo-drop-studs",
    description:
      "A center stone framed by a halo of smaller accents, set on a secure post back for all-day wear.",
    price: 27500,
    categoryId: "cat-earrings",
    material: "18k Gold Plated · Cubic Zirconia",
    variants: variants(["One Size"], "HDS"),
    status: "active",
    featured: true,
    createdAt: "2026-01-08T00:00:00.000Z",
  },
  {
    id: "prod-slim-hoops",
    name: "Slim Gold Hoops",
    slug: "slim-gold-hoops",
    description: "Lightweight everyday hoops with a polished finish that catches the light without shouting.",
    price: 19500,
    categoryId: "cat-earrings",
    material: "18k Gold Plated Brass",
    variants: variants(["Small", "Medium"], "SGH"),
    status: "active",
    createdAt: "2026-01-09T00:00:00.000Z",
  },
  {
    id: "prod-cascade-drops",
    name: "Cascade Drop Earrings",
    slug: "cascade-drop-earrings",
    description: "Tiered stone drops designed for occasion wear, moving gently with every turn of the head.",
    price: 39000,
    categoryId: "cat-earrings",
    material: "Rhodium Plated · Cubic Zirconia",
    variants: variants(["One Size"], "CDE"),
    status: "active",
    createdAt: "2026-01-10T00:00:00.000Z",
  },
  {
    id: "prod-linked-bangle",
    name: "Linked Chain Bangle",
    slug: "linked-chain-bangle",
    description: "A structured chain-link bangle with a secure clasp, sized to sit comfortably at the wrist.",
    price: 33500,
    categoryId: "cat-bracelets",
    material: "18k Gold Plated Brass",
    variants: variants(["Small", "Medium", "Large"], "LCB"),
    status: "active",
    createdAt: "2026-01-11T00:00:00.000Z",
  },
  {
    id: "prod-tennis-bracelet",
    name: "Classic Tennis Bracelet",
    slug: "classic-tennis-bracelet",
    description: "A continuous line of brilliant-cut stones in a timeless setting, dressy enough for any occasion.",
    price: 47000,
    categoryId: "cat-bracelets",
    material: "925 Sterling Silver · Cubic Zirconia",
    variants: variants(['6.5"', '7"'], "CTB"),
    status: "active",
    featured: true,
    createdAt: "2026-01-12T00:00:00.000Z",
  },
  {
    id: "prod-bridal-set-serena",
    name: "Serena Bridal Set",
    slug: "serena-bridal-set",
    description:
      "A matching necklace and earring set designed for bridal wear, with layered stone detailing that photographs beautifully.",
    price: 89000,
    compareAtPrice: 99000,
    categoryId: "cat-bridal",
    material: "Rhodium Plated · Cubic Zirconia",
    variants: variants(["One Size"], "SBS"),
    status: "active",
    featured: true,
    createdAt: "2026-01-03T00:00:00.000Z",
  },
  {
    id: "prod-bridal-tikka",
    name: "Layla Maang Tikka",
    slug: "layla-maang-tikka",
    description: "A delicate centre-parting piece finished with a teardrop stone, made for bridal and formal occasions.",
    price: 41000,
    categoryId: "cat-bridal",
    material: "18k Gold Plated · Kundan Work",
    variants: variants(["One Size"], "LMT"),
    status: "active",
    createdAt: "2026-01-02T00:00:00.000Z",
  },
  {
    id: "prod-draft-signet",
    name: "Engraved Signet Ring",
    slug: "engraved-signet-ring",
    description: "A bold, polished signet ring ready for personal engraving. Currently in final sampling.",
    price: 29500,
    categoryId: "cat-rings",
    material: "18k Gold Plated Brass",
    variants: variants(["Size 6", "Size 7"], "ESR"),
    status: "draft",
    createdAt: "2026-01-13T00:00:00.000Z",
  },
];
